- name: Install NGINX
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Create a file using secret
  copy:
    content: "This is a protected password: {{ nginx_custom_password }}"
    dest: /etc/nginx/secret.txt

